import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LefSideBar from "../components/shared/LefSideBar";
import Header from "../components/shared/Header";
import { dark, neobrutalism } from "@clerk/themes";
import BottomBar from "../components/shared/BottomBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        signIn: { baseTheme: neobrutalism },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <header>
            <Header />
          </header>
          <main className="flex flex-row ">
            <LefSideBar />
            <section className="min-h-screen">{children}</section>
          </main>
          <BottomBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
